## Virtualservice for exposing excalidraw service via port 80
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: excalidraw
  namespace: excalidraw # Namespace of VirtualService need to be the same as application namespace
spec:
  hosts:
  - "excalidraw.localhost" # Domain name of the service excalidraw
  gateways:
  - istio-system/istio-ingress-gateway # This should be the name of associated gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: excalidraw.excalidraw.svc.cluster.local # Service of excalidraw deployment
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: excalidraw
  namespace: excalidraw # Namespace of VirtualService need to be the same as application namespace
spec:
  host: excalidraw.excalidraw.svc.cluster.local # Service of excalidraw deployment
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL # Enable mutual TLS