## This will enable mutual-tls between service in excalidraw
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: excalidraw
  namespace: excalidraw
spec:
  mtls:
    mode: STRICT