## Ingress resource to expose excalidraw deployment from your local machine
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx" # comment this out, if you want to use traefik instead
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: excalidraw
  namespace: excalidraw ## ingress resource must be deployed in the same namespace as excalidraw
spec:
  rules:
  - host: excalidraw.localhost ## domain name of excalidraw
    http:
      paths:
      - path: /
        backend:
          serviceName: excalidraw
          servicePort: 80

