version: "3"
services:
  mongodb0:
    image: mongo
    container_name: mongodb0
    hostname: mongodb0
    expose:
      - 27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - data-0:/data/db
    networks:
      - mongo
      - confluent   

  mongodb1:
    image: mongo
    container_name: mongodb1
    hostname: mongodb1
    expose:
      - 27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - data-1:/data/db
    networks:
      - mongo
      - confluent   

  mongodb2:
    image: mongo
    container_name: mongodb2
    hostname: mongodb2
    expose:
      - 27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - data-2:/data/db
    networks:
      - mongo
      - confluent   

  mongoclient:
    image: mongoclient/mongoclient
    container_name: mongoclient
    hostname: mongoclient
    ports:
      - 3000:3000
    restart: always
    networks:
      - mongo
      - confluent     

volumes:
  data-0:
  data-1:
  data-2:

networks:
  mongo:
  confluent: