apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: confluent
spec:
  shortDescription: Interact with Confluent Platform
  description: |
    The official kubectl plugin for Confluent Platform
  version: v0.174.5-1-g9e44058
  homepage: https://github.com/confluentinc/kubectl-plugin/
  platforms:
    - uri: https://github.com/conflunetinc/releases/download/kubectl-confluent-darwin-amd64.tar.gz
      sha256: d6510c5b3c4dd0dd8957e589a92166ca3d4673220d8e09e78677ee2be5849fce
      files:
        - from: "*"
          to: "."
      bin: "./kubectl-confluent"
      selector:
        matchLabels:
          os: darwin
          arch: amd64
    - uri: https://github.com/conflunetinc/releases/download/kubectl-confluent-linux-amd64.tar.gz
      sha256: 729b296fc1ff80e63ad257c899671499d45e1316376b27ca20853b3159a3fbe8
      files:
        - from: "*"
          to: "."
      bin: "./kubectl-confluent"
      selector:
        matchLabels:
          os: linux
          arch: amd64
    - uri: https://github.com/conflunetinc/releases/download//kubectl-confluent-windows-amd64.tar.gz
      sha256: de9891cf0bdd9163d72b7d83debd28f117532f12649e35da5a85b8d37fe53f72
      files:
        - from: "*"
          to: "."
      bin: "./kubectl-confluent.exe"
      selector:
        matchLabels:
          os: windows
          arch: amd64
