apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: excalidraw
  namespace: excalidraw
spec:
  dnsNames:
    - infologistix-cnc.ddnss.org
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer