## Central istio-gateway for every applications running in azure cloud environment

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingress-gateway
  namespace: istio-system ## Gateway should be deployed in istio-system namespace
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port: ## enable domain names on port 80
      number: 80
      name: http
      protocol: HTTP
    hosts: ## Add more domain names here
    - "excalidraw.infologistix-cnc.ddnss.org"
    - "wekan.infologistix-cnc.ddnss.org"
    - "confluent.infologistix-cnc.ddnss.org"
    - "rancher.infologistix-cnc.ddnss.org"
    - "druid.infologistix-cnc.ddnss.org"
    - "superset.infologistix-cnc.ddnss.org"
    - "elastic.infologistix-cnc.ddnss.org"
    - "hadoop.infologistix-cnc.ddnss.org"
    - "zeppelin.infologistix-cnc.ddnss.org"
  - port: ## Enable tls on excalidraw domain name
      number: 443
      name: https-excalidraw
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-secret-excalidraw # must be the same as secret
    hosts:
    - "excalidraw.infologistix-cnc.ddnss.org"
  - port: ## Enable tls on wekan domain name
      number: 443
      name: https-wekan
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-secret-wekan # must be the same as secret
    hosts:
    - "wekan.infologistix-cnc.ddnss.org"
  - port: ## Enable tls on confluent domain name
      number: 443
      name: https-confluent
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-secret-confluent # must be the same as secret
    hosts:
    - "confluent.infologistix-cnc.ddnss.org"
  - port: ## Enable tls on rancher domain name
      number: 443
      name: https-rancher
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-secret-rancher # must be the same as secret
    hosts:
    - "rancher.infologistix-cnc.ddnss.org"
  - port: ## Enable tls on druid domain name
      number: 443
      name: https-druid
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-secret-druid # must be the same as secret
    hosts:
    - "druid.infologistix-cnc.ddnss.org"
  - port: ## Enable tls on superset domain name
      number: 443
      name: https-superset
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-secret-superset # must be the same as secret
    hosts:
    - "superset.infologistix-cnc.ddnss.org"
  - port: ## Enable tls on efk-stack domain name
      number: 443
      name: https-elastic
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-secret-elastic # must be the same as secret
    hosts:
    - "elastic.infologistix-cnc.ddnss.org"
