## Central istio-gateway for istio-addons running in your local machine

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingress-addon-gateway
  namespace: istio-system ## Gateway should be deployed in istio-system namespace
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port: ## enable domain names on port 80
      number: 80
      name: http
      protocol: HTTP
    hosts: ## Add more domain names here
    - "grafana.localhost"
    - "kiali.localhost"
    - "prometheus.localhost"
    - "jaeger.localhost"

######################################################### Grafana #############################################################
## Virtualservice for Grafana service
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: istio-system ## We define virtualservice in istio-system namespace since istio-addons are deployed in istio-system namespace
spec:
  hosts:
  - "grafana.localhost" ## domain name of grafana
  gateways:
  - istio-ingress-addon-gateway ## Name of istio-gateway
  http:
  - route:
    - destination:
        host: grafana ## Name of the service
        port:
          number: 3000

######################################################### Kiali #############################################################
## Virtualservice for Kiali service
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-vs
  namespace: istio-system ## We define virtualservice in istio-system namespace since istio-addons are deployed in istio-system namespace
spec:
  hosts:
  - "kiali.localhost" ## domain name of kiali
  gateways:
  - istio-ingress-addon-gateway ## Name of istio-gateway
  http:
  - route:
    - destination:
        host: kiali ## Name of the service
        port:
          number: 20001
######################################################### prometheus #############################################################
## Virtualservice for Prometheus service
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-vs
  namespace: istio-system ## We define virtualservice in istio-system namespace since istio-addons are deployed in istio-system namespace
spec:
  hosts:
  - "prometheus.localhost" ## domain name of prometheus
  gateways:
  - istio-ingress-addon-gateway ## Name of istio-gateway
  http:
  - route:
    - destination:
        host: prometheus ## Name of the service
        port:
          number: 9090
######################################################### jaeger #############################################################
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger-vs
  namespace: istio-system ## We define virtualservice in istio-system namespace since istio-addons are deployed in istio-system namespace
spec:
  hosts:
  - "jaeger.localhost" ## domain name of jaeger
  gateways:
  - istio-ingress-addon-gateway ## Name of istio-gateway
  http:
  - route:
    - destination:
        host: tracing ## Name of the service
        port:
          number: 80