## Central istio-gateway for every applications running in your local machine

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingress-gateway
  namespace: istio-system ## Gateway should be deployed in istio-system namespace
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port: ## enable domain names on port 80
      number: 80
      name: http
      protocol: HTTP
    hosts: ## Add more domain names here
    - "excalidraw.localhost"
    - "wekan.localhost"
    - "confluent.localhost"
    - "rancher.localhost"
    - "druid.localhost"
    - "superset.localhost"
    - "elastic.localhost"
    - "hadoop.localhost"
    - "zeppelin.localhost"
  - port: ## Enable tls on excalidraw domain name
      number: 443
      name: https-excalidraw
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-secret # must be the same as secret
    hosts:
    - "excalidraw.localhost"
  - port: ## Enable tls on wekan domain name
      number: 443
      name: https-wekan
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-secret # must be the same as secret
    hosts:
    - "wekan.localhost"
  - port: ## Enable tls on confluent domain name
      number: 443
      name: https-confluent
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-secret # must be the same as secret
    hosts:
    - "confluent.localhost"
  - port: ## Enable tls on rancher domain name
      number: 443
      name: https-rancher
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-secret # must be the same as secret
    hosts:
    - "rancher.localhost"
  - port: ## Enable tls on druid domain name
      number: 443
      name: https-druid
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-secret # must be the same as secret
    hosts:
    - "druid.localhost"
  - port: ## Enable tls on superset domain name
      number: 443
      name: https-superset
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-secret # must be the same as secret
    hosts:
    - "superset.localhost"
  - port: ## Enable tls on efk-stack domain name
      number: 443
      name: https-elastic
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tls-secret # must be the same as secret
    hosts:
    - "elastic.localhost"

